#DataSource Configuration
#PostgreSQL configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/security_app?sslmode=prefer&connect_timeout=10
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.open-in-view=true
spring.datasource.driver-class-name=org.postgresql.Driver
# Pool connections configuration (HikariCP)
spring.datasource.hikari.maximum-pool-size=16
spring.datasource.hikari.minimum-idle=4
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.leakDetectionThreshold=15000
# Otras configuraciones adicionales (opcional)
spring.datasource.hikari.pool-name=SDDCatalogConnectionPool